version: '3.9'

services:
  mysql:
    container_name: flask-mysql
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT_1}:3306"
      - "${MYSQL_PORT_2}:33060"