version: '3.9'

services:
  mysql:
    container_name: flask-mysql
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    ports:
      - "${DB_HOST}:${DB_PORT_1}:3306"
      - "${DB_HOST}:${DB_PORT_2}:33060"